name: connecting_dartisans
version: 0.1.0
description: Application to help dartisans connections.
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  logging: '>=0.9.2 <0.10.0'
  paper_elements: '>=0.6.0 <0.7.0'
  polymer: '>=0.15.0 <0.16.0'
  modern_charts: '>=0.1.1 <0.2.0'
  gex_webapp_kit_client:
    git: git://github.com/GeReinhart/dart-gex-webapp-kit-client.git  
  shelf: '>=0.5.6 <0.6.0'
  shelf_static: '>=0.2.1 <0.3.0'
dev_dependencies:
  unittest: ">=0.11.4 <0.12.0" 
  mockito: ">=0.8.1 <0.9.0"  
transformers:
- polymer:
    entry_points:
      - web/index.html
- $dart2js:
    commandLineOptions:
      - --enable-enum
      
      
